version: '3'

services:
  course-service:
    build: ./product
    volumes: 
      - ./product:/usr/src/app
    ports:
     - 8001:80
  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 8002:80
    depends_on:
      - course-service
  website1:
    image: php:apache
    volumes:
      - ./website1:/var/www/html
    ports:
      - 8003:80
    depends_on:
      - course-service
